#!/bin/bash

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Mert Koğuş

if [[ $ASK_API_URL == "" ]];then
    echo "ASK_API_URL environment variable is missing."
    exit 1
fi

if [[ $ASK_MODEL == "" ]];then
    echo "ASK_MODEL environment variable is missing."
    exit 1
fi

if [[ $ASK_API_KEY == "" ]];then
    echo "ASK_API_KEY environment variable is missing."
    exit 1
fi

args=""
stdin=""

if [[ $# != 0 ]]; then
  args="$*"
fi

if [[ ! -t 0 ]]; then
  stdin=$(cat)
fi

if [[ -z "$args" && -z "$stdin" ]]; then
    echo "Error: No input provided. Prompt is required either as an argument or through piped input."
    exit 1
elif [[ -n "$args" && -n "$stdin" ]]; then
    prompt="${args}, ${stdin}"
else
    prompt="${args}${stdin}"
fi

# echo "Prompt: $prompt"

ask() {
    local request=$(jq -n \
    --arg model "${ASK_MODEL}" \
    --arg prompt "${prompt}" \
    '{
    model: $model,
    messages: [
        {
        role: "system",
        content: "You are a CLI tool. Output plain text only. No
            yapping. Keep the output concise."
        },
        {
        role: "user",
        content: $prompt  
        }
    ]
    }')
    
    curl "${ASK_API_URL}" -s \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${ASK_API_KEY}" \
        -d "${request}" \
    | jq -r '.choices[0].message.content // .error.message'
}

ask


